// flow-typed signature: 7de18bd10c988287d44c5a2d61cd9cc2
// flow-typed version: <<STUB>>/@progress/kendo-react-excel-export_v^3.15.0/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@progress/kendo-react-excel-export'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@progress/kendo-react-excel-export' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@progress/kendo-react-excel-export/dist/cdn/js/kendo-react-excel-export' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/ColumnBase' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/ExcelExport' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/ExcelExportColumn' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/ExcelExportColumnGroup' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/ExcelExportData' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/main' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/ooxml/CellOptionsInterface' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/ooxml/ExporterColumns' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/ooxml/workbook' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/templates/ExcelExportFooter' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/templates/ExcelExportGroupFooter' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/es/templates/ExcelExportGroupHeader' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/ColumnBase' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/ExcelExport' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/ExcelExportColumn' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/ExcelExportColumnGroup' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/ExcelExportData' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/main' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/ooxml/CellOptionsInterface' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/ooxml/ExporterColumns' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/ooxml/workbook' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/templates/ExcelExportFooter' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/templates/ExcelExportGroupFooter' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/npm/templates/ExcelExportGroupHeader' {
  declare module.exports: any;
}

declare module '@progress/kendo-react-excel-export/dist/systemjs/kendo-react-excel-export' {
  declare module.exports: any;
}

// Filename aliases
declare module '@progress/kendo-react-excel-export/dist/cdn/js/kendo-react-excel-export.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/cdn/js/kendo-react-excel-export'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/ColumnBase.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/ColumnBase'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/ExcelExport.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/ExcelExport'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/ExcelExportColumn.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/ExcelExportColumn'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/ExcelExportColumnGroup.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/ExcelExportColumnGroup'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/ExcelExportData.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/ExcelExportData'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/main.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/main'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/ooxml/CellOptionsInterface.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/ooxml/CellOptionsInterface'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/ooxml/ExporterColumns.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/ooxml/ExporterColumns'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/ooxml/workbook.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/ooxml/workbook'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/templates/ExcelExportFooter.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/templates/ExcelExportFooter'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/templates/ExcelExportGroupFooter.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/templates/ExcelExportGroupFooter'>;
}
declare module '@progress/kendo-react-excel-export/dist/es/templates/ExcelExportGroupHeader.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/es/templates/ExcelExportGroupHeader'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/ColumnBase.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/ColumnBase'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/ExcelExport.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/ExcelExport'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/ExcelExportColumn.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/ExcelExportColumn'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/ExcelExportColumnGroup.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/ExcelExportColumnGroup'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/ExcelExportData.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/ExcelExportData'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/main.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/main'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/ooxml/CellOptionsInterface.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/ooxml/CellOptionsInterface'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/ooxml/ExporterColumns.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/ooxml/ExporterColumns'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/ooxml/workbook.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/ooxml/workbook'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/templates/ExcelExportFooter.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/templates/ExcelExportFooter'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/templates/ExcelExportGroupFooter.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/templates/ExcelExportGroupFooter'>;
}
declare module '@progress/kendo-react-excel-export/dist/npm/templates/ExcelExportGroupHeader.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/npm/templates/ExcelExportGroupHeader'>;
}
declare module '@progress/kendo-react-excel-export/dist/systemjs/kendo-react-excel-export.js' {
  declare module.exports: $Exports<'@progress/kendo-react-excel-export/dist/systemjs/kendo-react-excel-export'>;
}
