// flow-typed signature: eb08296a3c1e0c33bc6451cce165fa7a
// flow-typed version: <<STUB>>/imagemin-lint-staged_v^0.4.0/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'imagemin-lint-staged'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'imagemin-lint-staged' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'imagemin-lint-staged/bin' {
  declare module.exports: any;
}

declare module 'imagemin-lint-staged/lib/__tests__/index.spec' {
  declare module.exports: any;
}

declare module 'imagemin-lint-staged/lib' {
  declare module.exports: any;
}

// Filename aliases
declare module 'imagemin-lint-staged/bin/index' {
  declare module.exports: $Exports<'imagemin-lint-staged/bin'>;
}
declare module 'imagemin-lint-staged/bin/index.js' {
  declare module.exports: $Exports<'imagemin-lint-staged/bin'>;
}
declare module 'imagemin-lint-staged/lib/__tests__/index.spec.js' {
  declare module.exports: $Exports<'imagemin-lint-staged/lib/__tests__/index.spec'>;
}
declare module 'imagemin-lint-staged/lib/index' {
  declare module.exports: $Exports<'imagemin-lint-staged/lib'>;
}
declare module 'imagemin-lint-staged/lib/index.js' {
  declare module.exports: $Exports<'imagemin-lint-staged/lib'>;
}
