// flow-typed signature: 27705d358b79fc51c4ad3d4dacb058bb
// flow-typed version: <<STUB>>/react-js-pagination_v3.0.3/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-js-pagination'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-js-pagination' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-js-pagination/devServer' {
  declare module.exports: any;
}

declare module 'react-js-pagination/dist/Page' {
  declare module.exports: any;
}

declare module 'react-js-pagination/dist/Pagination' {
  declare module.exports: any;
}

declare module 'react-js-pagination/src/components/Page' {
  declare module.exports: any;
}

declare module 'react-js-pagination/src/components/Page.test' {
  declare module.exports: any;
}

declare module 'react-js-pagination/src/components/Pagination' {
  declare module.exports: any;
}

declare module 'react-js-pagination/src/components/Pagination.test' {
  declare module.exports: any;
}

declare module 'react-js-pagination/src/example/App' {
  declare module.exports: any;
}

declare module 'react-js-pagination/src/example/dist/bundle' {
  declare module.exports: any;
}

declare module 'react-js-pagination/src/example' {
  declare module.exports: any;
}

declare module 'react-js-pagination/test-setup' {
  declare module.exports: any;
}

declare module 'react-js-pagination/webpack.config.dev' {
  declare module.exports: any;
}

declare module 'react-js-pagination/webpack.config.prod' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-js-pagination/devServer.js' {
  declare module.exports: $Exports<'react-js-pagination/devServer'>;
}
declare module 'react-js-pagination/dist/Page.js' {
  declare module.exports: $Exports<'react-js-pagination/dist/Page'>;
}
declare module 'react-js-pagination/dist/Pagination.js' {
  declare module.exports: $Exports<'react-js-pagination/dist/Pagination'>;
}
declare module 'react-js-pagination/src/components/Page.js' {
  declare module.exports: $Exports<'react-js-pagination/src/components/Page'>;
}
declare module 'react-js-pagination/src/components/Page.test.js' {
  declare module.exports: $Exports<'react-js-pagination/src/components/Page.test'>;
}
declare module 'react-js-pagination/src/components/Pagination.js' {
  declare module.exports: $Exports<'react-js-pagination/src/components/Pagination'>;
}
declare module 'react-js-pagination/src/components/Pagination.test.js' {
  declare module.exports: $Exports<'react-js-pagination/src/components/Pagination.test'>;
}
declare module 'react-js-pagination/src/example/App.js' {
  declare module.exports: $Exports<'react-js-pagination/src/example/App'>;
}
declare module 'react-js-pagination/src/example/dist/bundle.js' {
  declare module.exports: $Exports<'react-js-pagination/src/example/dist/bundle'>;
}
declare module 'react-js-pagination/src/example/index' {
  declare module.exports: $Exports<'react-js-pagination/src/example'>;
}
declare module 'react-js-pagination/src/example/index.js' {
  declare module.exports: $Exports<'react-js-pagination/src/example'>;
}
declare module 'react-js-pagination/test-setup.js' {
  declare module.exports: $Exports<'react-js-pagination/test-setup'>;
}
declare module 'react-js-pagination/webpack.config.dev.js' {
  declare module.exports: $Exports<'react-js-pagination/webpack.config.dev'>;
}
declare module 'react-js-pagination/webpack.config.prod.js' {
  declare module.exports: $Exports<'react-js-pagination/webpack.config.prod'>;
}
