// flow-typed signature: 09d5a07443297ba6435da2bbebf08e84
// flow-typed version: <<STUB>>/redux-persist-seamless-immutable_v^2.0.0/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist-seamless-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist-seamless-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'redux-persist-seamless-immutable/lib/helpers' {
  declare module.exports: any;
}

declare module 'redux-persist-seamless-immutable/lib' {
  declare module.exports: any;
}

declare module 'redux-persist-seamless-immutable/lib/reconciler' {
  declare module.exports: any;
}

declare module 'redux-persist-seamless-immutable/lib/transformer' {
  declare module.exports: any;
}

// Filename aliases
declare module 'redux-persist-seamless-immutable/lib/helpers.js' {
  declare module.exports: $Exports<'redux-persist-seamless-immutable/lib/helpers'>;
}
declare module 'redux-persist-seamless-immutable/lib/index' {
  declare module.exports: $Exports<'redux-persist-seamless-immutable/lib'>;
}
declare module 'redux-persist-seamless-immutable/lib/index.js' {
  declare module.exports: $Exports<'redux-persist-seamless-immutable/lib'>;
}
declare module 'redux-persist-seamless-immutable/lib/reconciler.js' {
  declare module.exports: $Exports<'redux-persist-seamless-immutable/lib/reconciler'>;
}
declare module 'redux-persist-seamless-immutable/lib/transformer.js' {
  declare module.exports: $Exports<'redux-persist-seamless-immutable/lib/transformer'>;
}
