// flow-typed signature: ae8cd58c4ee3c5403bee33d1650462f3
// flow-typed version: <<STUB>>/seamless-immutable_vv7.1.4/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'seamless-immutable'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'seamless-immutable' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'seamless-immutable/seamless-immutable.development' {
  declare module.exports: any;
}

declare module 'seamless-immutable/seamless-immutable.development.min' {
  declare module.exports: any;
}

declare module 'seamless-immutable/seamless-immutable.production.min' {
  declare module.exports: any;
}

declare module 'seamless-immutable/src/seamless-immutable' {
  declare module.exports: any;
}

// Filename aliases
declare module 'seamless-immutable/seamless-immutable.development.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.development'>;
}
declare module 'seamless-immutable/seamless-immutable.development.min.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.development.min'>;
}
declare module 'seamless-immutable/seamless-immutable.production.min.js' {
  declare module.exports: $Exports<'seamless-immutable/seamless-immutable.production.min'>;
}
declare module 'seamless-immutable/src/seamless-immutable.js' {
  declare module.exports: $Exports<'seamless-immutable/src/seamless-immutable'>;
}
