// flow-typed signature: 2dbb87a68de19ca6ed53466a15dc72b7
// flow-typed version: <<STUB>>/redux-persist/integration/react_vv6.0.0/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'redux-persist/integration/react'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'redux-persist/integration/react' {
  declare module.exports: any;
}
