// flow-typed signature: 3877f7617b958704f1a3d310d728a16b
// flow-typed version: <<STUB>>/react-bootstrap/Modal_vv1.0.0-beta.16/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap/Modal'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap/Modal' {
  declare module.exports: any;
}
