// flow-typed signature: f705d58b254cbf0e7a9c184c212b977b
// flow-typed version: <<STUB>>/react-bootstrap/Spinner_vv1.0.0-beta.16/flow_v0.106.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-bootstrap/Spinner'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-bootstrap/Spinner' {
  declare module.exports: any;
}
